# Generated by Django 4.2.1 on 2023-05-14 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_category_slug_genre_slug_alter_title_category_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews.category'),
        ),
    ]
