# Generated by Django 3.2 on 2023-05-16 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20230516_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(default='Без категории', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='titles', to='reviews.category'),
        ),
    ]
